### ISSUE TITLE
"WithheldInCountries" still string not []string

### ISSUE THREAD

**Issue by deliverwow** [ChimeraCoder/anaconda#100]
The field "withheld_in_countries" in Twitter Json structures (`WithheldInCountries` in `User`) is still `string` not `[]string` (command GetUserTimeline), current version cannot unmarshal structures because of this issue.

**Comment by ChimeraCoder** [comment]
Ugh, this is super annoying. I really hate that Twitter returns inconsistently-structured responses. Sorry about that.

Do you have a sample request that returns a `string` instead of a `[]string` here, just for posterity? I'll revert the change. It's a shame we'll have to go back to an `interface{}`, but that's the best we can do.

**Comment by muesli** [comment]
@deliverwow: Is this still an issue?

**Comment by muesli** [comment]
From a few tests and according to Twitter's documentation this should always return an array of strings. I'm going to close this ticket, but please let us know if you can still reproduce this. Thanks for you report!
